// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPhongKham.Models;

#nullable disable

namespace WebPhongKham.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240920095606_DiaChiIsNotRequire")]
    partial class DiaChiIsNotRequire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPhongKham.Models.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idLoaiTinh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idLoaiTinh");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("WebPhongKham.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SoTien")
                        .HasColumnType("real");

                    b.Property<int?>("idDiaChi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idDiaChi");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("WebPhongKham.Models.LoaiTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiTinhs");
                });

            modelBuilder.Entity("WebPhongKham.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("WebPhongKham.Models.DiaChi", b =>
                {
                    b.HasOne("WebPhongKham.Models.LoaiTinh", "LoaiTinh")
                        .WithMany()
                        .HasForeignKey("idLoaiTinh");

                    b.Navigation("LoaiTinh");
                });

            modelBuilder.Entity("WebPhongKham.Models.KhachHang", b =>
                {
                    b.HasOne("WebPhongKham.Models.DiaChi", "DiaChi")
                        .WithMany()
                        .HasForeignKey("idDiaChi");

                    b.Navigation("DiaChi");
                });
#pragma warning restore 612, 618
        }
    }
}
